# Generated by Django 3.1.5 on 2021-01-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20210128_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
