# Generated by Django 3.1.5 on 2021-02-01 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0004_auto_20210201_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='population',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300),
        ),
    ]
