# Generated by Django 3.1.5 on 2021-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20210201_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
